# Generated by Django 3.1.7 on 2021-03-04 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catflap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('CL', 'Closed'), ('OI', 'Opened Inward'), ('OO', 'Opened Outward')], max_length=2)),
                ('catflap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catflap.catflap')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
