# Generated by Django 3.1.7 on 2021-03-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catflap", "0002_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CL", "Closed"),
                    ("O", "Opened"),
                    ("OI", "Opened Inward"),
                    ("OO", "Opened Outward"),
                ],
                max_length=2,
            ),
        ),
    ]
