# Generated by Django 3.1.7 on 2021-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catflap", "0003_add_generic_opened_state_to_event_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CL", "Closed"),
                    ("O", "Opened"),
                    ("OC", "Opened Closed"),
                    ("OI", "Opened Inward"),
                    ("OO", "Opened Outward"),
                ],
                max_length=2,
            ),
        ),
    ]
