# Generated by Django 3.1.7 on 2021-04-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catflap', '0003_add_generic_opened_state_to_event_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='catflap',
            name='cat_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
