# Generated by Django 3.1.7 on 2021-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catflap", "0005_add_cat_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catflap",
            name="cat_name",
            field=models.CharField(default="Cat", max_length=64),
        ),
    ]
