# Generated by Django 3.1.7 on 2021-04-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catflap", "0006_add_default_cat_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualStatusUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "catflap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catflap.catflap",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
