# Generated by Django 3.1.7 on 2021-04-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catflap", "0007_manualstatusupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualstatusupdate",
            name="cat_inside",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
