# Generated by Django 3.1.7 on 2021-04-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catflap", "0009_catflap_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="catflap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="catflap.catflap",
            ),
        ),
    ]
